version: '3.9'
services:
  postgres:
    image: postgres:15
    ports:
      - 6500:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

      